version: '3.9'
services: 
  ashu-springboot: 
    image: ashuspring:tomcatv1  # if this image is not present then only it will build 
    build: 
      context: .  # location of dockerfile 
      dockerfile:  Dockerfile # name of dockerfile
    container_name: ashuspringc1 
    ports:
    - 3011:8080  
# above steps have merging of build and run ok
  